---
- name: Install Jenkins on local machine
  hosts: localhost
  become: true
  vars:
    jenkins_apt_key_url: "https://pkg.jenkins.io/debian/jenkins.io.key"
    jenkins_apt_repo: "deb https://pkg.jenkins.io/debian-stable binary/"
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - openjdk-11-jdk
        - gnupg2

    - name: Add Jenkins apt key
      apt_key:
        url: "{{ jenkins_apt_key_url }}"

    - name: Add Jenkins apt repository
      apt_repository:
        repo: "{{ jenkins_apt_repo }}"
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
